var eventArray = {
    "events": [
      {
        "eventName": "South Bay Art1",
        "eventType": "Art",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/art1.jpg"
      },
      {
        "eventName": "South Bay Art2",
        "eventType": "Art",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/art2.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Art",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/art3.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Art",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/art4.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Hiking",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/hike1.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Hiking",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/hike2.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Hiking",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/hike3.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Hiking",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/hike4.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Health",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/health1.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Health",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/health2.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Health",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/health3.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Health",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/health4.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Tech",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/tech1.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Tech",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/tech2.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Tech",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/tech3.jpg"
      },
      {
        "eventName": "South Bay Art",
        "eventType": "Tech",
        "hostName": "Jennifer",
        "phoneNumber": "555-555-5555",
        "eAddress": "jeniffer@gmail.com",
        "companyName": "",
        "startTime": "5 Jun 2016 @ 3:30 PM",
        "endTime": "5 Jun 2016 @ 5:30 PM",
        "address": ["San Pedro Square Market", "87 North street", "San Jose", "CA"],
        "description": "This is a joint event organized by Founders Floor and Lifograph. Food, beer and wine are provided. You must purchase a ticket to attend",
        "image": "images/tech4.jpg"
      },
    ]
}
